language: java
jdk:
  - oraclejdk8

before_install:
  - cd osuCelebrity-parent

# we're not installing anything
install: true

before_script:
  - pip install --user codecov

script:
  - mvn verify -Dmaven.javadoc.skip=true -B -V
    
after_success:
  - codecov

cache:
  directories:
    - $HOME/.m2/repository
    
notifications:
  slack: osucelebrity:qK7sYUDrRp321vDlWK76KEu1