language: java
jdk:
  - oraclejdk8

before_install:
  - git clone https://github.com/Tillerino/osuApiConnector.git
  - cd osuApiConnector
  - mvn -fosuApiConnector/pom.xml -DskipTests=true -Dmaven.javadoc.skip=true -Dversions.skip=true -Dlombok.delombok.skip=true -Dfindbugs.skip=true install
  - cd ../osuCelebrity-parent

# we're not installing anything
install: true

before_script:
  - pip install --user codecov

script:
  - mvn verify -Dmaven.javadoc.skip=true -B -V
    
after_success:
  - codecov

cache:
  directories:
    - $HOME/.m2/repository