package me.reddev.osucelebrity.osuapi;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.tillerino.osuApiModel.OsuApiUser;
import org.tillerino.osuApiModel.types.GameMode;
import org.tillerino.osuApiModel.types.UserId;

import java.io.Serializable;
import java.util.StringTokenizer;

import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.PrimaryKey;

@PersistenceCapable(objectIdClass = ApiUser.ComposedIdKey.class)
@Getter
@ToString
public class ApiUser {
  @PrimaryKey
  @Getter(onMethod = @__(@UserId))
  @UserId
  private int userId;

  @GameMode
  @Getter(onMethod = @__(@GameMode))
  @PrimaryKey
  private int gameMode;

  @Setter
  long downloaded;

  @Setter
  private int rank;

  @Setter
  private double pp;

  @Setter
  private int playCount;

  @Setter
  private double level;

  @Setter
  private double accuracy;

  @Setter
  private String country;

  /**
   * see http://www.datanucleus.org/products/accessplatform_3_3/jdo/primary_key.html
   */
  public static class ComposedIdKey implements Serializable {
    private static final long serialVersionUID = 1L;

    public int userId;
    public int gameMode;

    public ComposedIdKey() {}

    /**
     * Constructor accepting same input as generated by toString().
     */
    public ComposedIdKey(String value) {
      StringTokenizer token = new StringTokenizer(value, "::");
      this.userId = Integer.parseInt(token.nextToken());
      this.gameMode = Integer.parseInt(token.nextToken());
    }

    /**
     * compares all fields.
     */
    public boolean equals(Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof ComposedIdKey)) {
        return false;
      }
      ComposedIdKey key = (ComposedIdKey) obj;

      return userId == key.userId && gameMode == key.gameMode;
    }

    public int hashCode() {
      return userId ^ gameMode;
    }

    public String toString() {
      return this.userId + "::" + this.gameMode;
    }
  }

  /**
   * Constructs a new instance copying data from an api object.
   * 
   * @param downloadedData The object to base all data on.
   * @param downloaded current time
   */
  public ApiUser(OsuApiUser downloadedData, long downloaded) {
    super();
    this.userId = downloadedData.getUserId();
    this.gameMode = downloadedData.getMode();
    update(downloadedData, downloaded);
  }

  /**
   * Updates the contained data copying data from an api object.
   * 
   * @param downloadedData The object to base all data on.
   * @param downloaded current time
   */
  public void update(OsuApiUser downloadedData, long downloaded) {
    this.downloaded = downloaded;

    this.setRank(downloadedData.getRank());
    this.setPp(downloadedData.getPp());
    this.setPlayCount(downloadedData.getPlayCount());
    this.setLevel(downloadedData.getLevel());
    this.setAccuracy(downloadedData.getAccuracy());
    this.setCountry(downloadedData.getCountry());
  }
}
